### ISSUE TITLE
请问示例的bag文件是什么雷达扫描的呢？

### ISSUE THREAD

**Issue by KevinLee752** [jyakaranda/A-LeGO-LOAM#3]
Hi, 
   非常感谢您的分享。我想问下，这里给的示例bag文件： test_0515.bag，是用什么雷达扫描的呢？我想用这个数据去测试下作者原版的LeGO-LOAM代码，需要相应的做些什么样的修改呢？期待回复，非常感谢！

**Comment by jyakaranda** [comment]
你好
1. 用的是镭神智能C16
2. 数据可以测试LeGO-LOAM，把utility.h里的雷达参数设成5hz对应的参数即可

**Comment by KevinLee752** [comment]
不好意思，再次打扰您一下：这个示例数据的IMU与雷达点云是对齐的吗（包括时间和坐标系）？以及，是否有可能，您能够共享更多一些的示例数据呢？
